# Generated by Django 6.0 on 2026-08-20 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emr', '0080_alter_activitydefinition_category_and_more'),
        ('facility', '0485_rename_patientmobileotp_mobileotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DVDMSDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('drug_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('brand_id', models.CharField(blank=True, default='', max_length=50)),
                ('group_id', models.CharField(blank=True, default='', max_length=50)),
                ('sub_group_id', models.CharField(blank=True, default='', max_length=50)),
                ('unit_id', models.CharField(blank=True, default='', max_length=50)),
                ('drug_category', models.CharField(blank=True, default='', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DVDMS Drugs',
            },
        ),
        migrations.CreateModel(
            name='DVDMSInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('eaushadhi_institute_id', models.CharField(max_length=50, unique=True)),
                ('eaushadhi_institute_name', models.CharField(max_length=255)),
                ('eaushadhi_user_ref_id', models.CharField(max_length=50)),
                ('schema_version', models.CharField(default='1.0', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dvdms_institute', to='facility.facility')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DVDMS Institutes',
            },
        ),
        migrations.CreateModel(
            name='DVDMSRecordOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_orders', to='care_dvdms.dvdmsinstitute')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dvdms_record_order', to='emr.requestorder')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DVDMS Record Orders',
            },
        ),
        migrations.CreateModel(
            name='DVDMSRecordItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('drug', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='record_item_order', to='care_dvdms.dvdmsdrug')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_item_orders', to='care_dvdms.dvdmsinstitute')),
                ('supply_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dvdms_record_item_order', to='emr.supplyrequest')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('record_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_orders', to='care_dvdms.dvdmsrecordorder')),
            ],
            options={
                'verbose_name_plural': 'DVDMS Record Item Orders',
            },
        ),
        migrations.CreateModel(
            name='DVDMSStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('eaushadhi_store_id', models.CharField(max_length=50)),
                ('eaushadhi_store_name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_mappings', to='care_dvdms.dvdmsinstitute')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dvdms_store_mappings', to='emr.facilitylocation')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DVDMS Stores',
            },
        ),
        migrations.AddField(
            model_name='dvdmsrecordorder',
            name='institute_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_orders', to='care_dvdms.dvdmsstore'),
        ),
        migrations.CreateModel(
            name='DVDMSSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('eaushadhi_warehouse_id', models.CharField(max_length=50)),
                ('eaushadhi_warehouse_name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_mappings', to='care_dvdms.dvdmsinstitute')),
                ('supplier', models.ForeignKey(limit_choices_to={'org_type': 'product_supplier'}, on_delete=django.db.models.deletion.PROTECT, related_name='dvdms_supplier_mappings', to='emr.organization')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DVDMS Suppliers',
            },
        ),
        migrations.AddField(
            model_name='dvdmsrecordorder',
            name='institute_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_orders', to='care_dvdms.dvdmssupplier'),
        ),
        migrations.CreateModel(
            name='DVDMSSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('triggered_by', models.CharField(choices=[('user', 'User'), ('cron', 'Cron'), ('retry', 'Retry')], default='user', max_length=20)),
                ('sync_type', models.CharField(choices=[('save_indent', 'Save Indent'), ('track_indent', 'Track Indent'), ('acknowledge', 'Acknowledge')], max_length=20)),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=20)),
                ('http_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('api_response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='care_dvdms.dvdmsinstitute')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DVDMS Sync Logs',
            },
        ),
        migrations.CreateModel(
            name='DVDMSOutwardRecordOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='created', max_length=20)),
                ('eaushadhi_indent_no', models.CharField(blank=True, max_length=255, null=True)),
                ('eaushadhi_indent_status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('record_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outward_record', to='care_dvdms.dvdmsrecordorder')),
                ('sync_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outward_records', to='care_dvdms.dvdmssynclog')),
            ],
            options={
                'verbose_name_plural': 'DVDMS Outward Record Orders',
            },
        ),
        migrations.CreateModel(
            name='DVDMSProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('eaushadhi_drug_id', models.CharField(max_length=50)),
                ('mapping_type', models.CharField(choices=[('default_mapping', 'Default Mapping'), ('manual_mapping', 'Manual Mapping')], db_index=True, default='manual_mapping', max_length=20)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('drug', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='product_mapping', to='care_dvdms.dvdmsdrug')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='care_dvdms.dvdmsinstitute')),
                ('product_knowledge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dvdms_product_mappings', to='emr.productknowledge')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DVDMS Product Mappings',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('institute', 'eaushadhi_drug_id'), name='uniq_institute_eaushadhi_drug_id')],
            },
        ),
        migrations.AddConstraint(
            model_name='dvdmsstore',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('institute', 'location'), name='uniq_institute_location'),
        ),
        migrations.AddConstraint(
            model_name='dvdmsstore',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('is_default', True)), fields=('institute', 'is_default'), name='uniq_default_store_per_institute'),
        ),
        migrations.AddConstraint(
            model_name='dvdmssupplier',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('institute', 'supplier'), name='uniq_institute_supplier'),
        ),
        migrations.AddConstraint(
            model_name='dvdmssupplier',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('is_default', True)), fields=('institute', 'is_default'), name='uniq_default_supplier_per_institute'),
        ),
    ]
