# Generated by Django 6.0 on 2026-09-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_dvdms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvdmsinwarditemrecord',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
