# Generated by Django 6.0 on 2026-08-24 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_dvdms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DVDMSInwardRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('eaushadhi_issue_no', models.CharField(max_length=255)),
                ('eaushadhi_issue_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('received', 'Received'), ('partially_received', 'Partially Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('outward_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inward_records', to='care_dvdms.dvdmsoutwardrecordorder')),
                ('sync_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inward_records', to='care_dvdms.dvdmssynclog')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DVDMS Inward Records',
            },
        ),
        migrations.CreateModel(
            name='DVDMSInwardItemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('drug_id', models.CharField(max_length=50)),
                ('drug_name', models.CharField(max_length=500)),
                ('brand_id', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('received_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('partially_received', 'Partially Received'), ('rejected', 'Rejected'), ('damaged', 'Damaged')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('record_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inward_item_records', to='care_dvdms.dvdmsrecorditemorder')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('inward_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='care_dvdms.dvdmsinwardrecord')),
            ],
            options={
                'verbose_name_plural': 'DVDMS Inward Item Records',
            },
        ),
        migrations.AddConstraint(
            model_name='dvdmsinwardrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('outward_record', 'eaushadhi_issue_no'), name='uniq_outward_record_issue_no'),
        ),
        migrations.AddConstraint(
            model_name='dvdmsinwarditemrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('inward_record', 'record_order_item'), name='uniq_inward_record_item'),
        ),
    ]
