# Generated by Django 6.0 on 2026-08-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_dvdms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvdmsrecordorder',
            name='care_indent_no',
            field=models.CharField(blank=True, editable=False, max_length=32, unique=True),
        ),
    ]
