# Generated by Django 6.0 on 2026-08-21 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_dvdms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvdmsrecordorder',
            name='care_indent_no',
            field=models.CharField(blank=True, editable=False, max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='DVDMSCareIndentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=6)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_indent_sequences', to='care_dvdms.dvdmsinstitute')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('institute', 'financial_year'), name='uniq_institute_financial_year')],
            },
        ),
    ]
