# Generated by Django 6.0 on 2026-09-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_dvdms', '0002_dvdmsinwarditemrecord_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvdmsinwardrecord',
            name='eaushadhi_issue_status',
            field=models.CharField(choices=[('fetched', 'Fetched')], default='fetched', max_length=20),
        ),
    ]
