# Generated by Django 6.0 on 2026-08-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_dvdms', '0002_dvdmsinwardrecord_dvdmsinwarditemrecord_and_more'),
        ('care_dvdms', '0002_dvdmsrecordorder_care_indent_no_and_more'),
    ]

    operations = []
