# Generated by Django 6.0 on 2026-08-13 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_dvdms', '0002_dvdmssupplier'),
        ('emr', '0080_alter_activitydefinition_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DVDMSStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('eaushadhi_store_id', models.CharField(max_length=50)),
                ('eaushadhi_store_name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_mappings', to='care_dvdms.dvdmsinstitute')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dvdms_store_mappings', to='emr.facilitylocation')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DVDMS Stores',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('institute', 'location'), name='uniq_institute_location'), models.UniqueConstraint(condition=models.Q(('deleted', False), ('is_default', True)), fields=('institute', 'is_default'), name='uniq_default_store_per_institute')],
            },
        ),
    ]
