# Generated by Django 6.0 on 2026-09-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_dvdms', '0003_alter_dvdmsinwardrecord_eaushadhi_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvdmsrecorddelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('received', 'Received'), ('acknowledged', 'Acknowledged'), ('acknowledgement_failed', 'Acknowledgement Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
