# Generated by Django 6.0 on 2026-08-17 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_dvdms', '0003_dvdmsstore'),
        ('emr', '0080_alter_activitydefinition_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DVDMSDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('brand_id', models.CharField(blank=True, default='', max_length=50)),
                ('group_id', models.CharField(blank=True, default='', max_length=50)),
                ('sub_group_id', models.CharField(blank=True, default='', max_length=50)),
                ('unit_id', models.CharField(blank=True, default='', max_length=50)),
                ('drug_category', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DVDMSRecordOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_orders', to='care_dvdms.dvdmsinstitute')),
                ('institute_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_orders', to='care_dvdms.dvdmsstore')),
                ('institute_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_orders', to='care_dvdms.dvdmssupplier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dvdms_record_orders', to='emr.requestorder')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DVDMS Record Orders',
            },
        ),
        migrations.CreateModel(
            name='DVDMSRecordItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('drug', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record_item_order', to='care_dvdms.dvdmsdrug')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_item_orders', to='care_dvdms.dvdmsinstitute')),
                ('supply_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dvdms_record_item_orders', to='emr.supplyrequest')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('record_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_orders', to='care_dvdms.dvdmsrecordorder')),
            ],
            options={
                'verbose_name_plural': 'DVDMS Record Item Orders',
            },
        ),
    ]
