# Generated by Django 6.0 on 2026-08-26 06:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_dvdms', '0003_merge_20260825_1430'),
        ('emr', '0080_alter_activitydefinition_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DVDMSRecordDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('delivery_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dvdms_record_delivery', to='emr.deliveryorder')),
                ('inward_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record_delivery', to='care_dvdms.dvdmsinwardrecord')),
                ('record_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_deliveries', to='care_dvdms.dvdmsrecordorder')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DVDMS Record Deliveries',
            },
        ),
        migrations.CreateModel(
            name='DVDMSRecordItemDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('quantity_dispatched', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_accepted', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_damaged', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_short', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ACTIVE', 'Active'), ('REVERSED', 'Reversed ')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('inward_record_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='item_delivery', to='care_dvdms.dvdmsinwarditemrecord')),
                ('record_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_deliveries', to='care_dvdms.dvdmsrecorddelivery')),
                ('supply_delivery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dvdms_record_item_delivery', to='emr.supplydelivery')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DVDMS Record Item Deliveries',
            },
        ),
    ]
