# Generated by Django 6.0 on 2026-09-21 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_dvdms', '0004_alter_dvdmsrecorddelivery_status'),
        ('emr', '0082_remove_encounter_encounter_class_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dvdmsrecordorder',
            name='uniq_order_active_record_order',
        ),
        migrations.AddConstraint(
            model_name='dvdmsrecordorder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), models.Q(('status__in', ['cancelled']), _negated=True)), fields=('order',), name='uniq_order_active_record_order'),
        ),
    ]
