# Generated by Django 6.0 on 2026-08-18 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_dvdms', '0004_dvdmsdrug_dvdmsrecordorder_dvdmsrecorditemorder'),
        ('emr', '0080_alter_activitydefinition_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvdmsrecorditemorder',
            name='supply_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dvdms_record_item_order', to='emr.supplyrequest'),
        ),
        migrations.AlterField(
            model_name='dvdmsrecordorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dvdms_record_order', to='emr.requestorder'),
        ),
        migrations.AlterField(
            model_name='dvdmsrecordorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='DVDMSSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('triggered_by', models.CharField(choices=[('user', 'User'), ('cron', 'Cron'), ('retry', 'Retry')], default='user', max_length=20)),
                ('sync_type', models.CharField(choices=[('save_indent', 'Save Indent'), ('track_indent', 'Track Indent'), ('acknowledge', 'Acknowledge')], max_length=20)),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=20)),
                ('http_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('api_response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='care_dvdms.dvdmsinstitute')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DVDMS Sync Logs',
            },
        ),
        migrations.CreateModel(
            name='DVDMSOutwardRecordOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('eaushadhi_indent_no', models.CharField(blank=True, max_length=255, null=True)),
                ('eaushadhi_indent_status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('record_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outward_record', to='care_dvdms.dvdmsrecordorder')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('sync_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outward_records', to='care_dvdms.dvdmssynclog')),
            ],
            options={
                'verbose_name_plural': 'DVDMS Outward Record Orders',
            },
        ),
    ]
