# Generated by Django 6.0 on 2026-08-26 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_dvdms', '0004_dvdmsrecorddelivery_dvdmsrecorditemdelivery'),
        ('emr', '0080_alter_activitydefinition_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dvdmsrecorditemdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_dispatched__gte', 0)), name='record_item_delivery_quantity_dispatched_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='dvdmsrecorditemdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_accepted__gte', 0)), name='record_item_delivery_quantity_accepted_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='dvdmsrecorditemdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_damaged__gte', 0)), name='record_item_delivery_quantity_damaged_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='dvdmsrecorditemdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_short__gte', 0)), name='record_item_delivery_quantity_short_gte_0'),
        ),
    ]
