# Generated by Django 6.0 on 2026-08-26 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_dvdms', '0005_dvdmsrecorditemdelivery_record_item_delivery_quantity_dispatched_gte_0_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dvdmsinwardrecord',
            name='uniq_outward_record_issue_no',
        ),
        migrations.AddField(
            model_name='dvdmsinwardrecord',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inward_records', to='care_dvdms.dvdmsinstitute'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dvdmsinwardrecord',
            name='outward_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inward_records', to='care_dvdms.dvdmsoutwardrecordorder'),
        ),
        migrations.AlterField(
            model_name='dvdmsrecorddelivery',
            name='record_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_deliveries', to='care_dvdms.dvdmsrecordorder'),
        ),
        migrations.AddConstraint(
            model_name='dvdmsinwardrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('institute', 'eaushadhi_issue_no'), name='uniq_institute_issue_no'),
        ),
    ]
