# Generated by Django 6.0 on 2026-08-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_dvdms', '0005_alter_dvdmsrecorditemorder_supply_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvdmsoutwardrecordorder',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='dvdmsrecordorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
