# Generated by Django 6.0 on 2026-08-27 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_dvdms", "0006_remove_dvdmsinwardrecord_uniq_outward_record_issue_no_and_more"),
        ("emr", "0080_alter_activitydefinition_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dvdmsrecordorder",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="dvdms_record_order", to="emr.requestorder"
            ),
        ),
        migrations.AddConstraint(
            model_name="dvdmsrecordorder",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted", False), models.Q(("status__in", ["cancelled", "rejected", "failed"]), _negated=True)
                ),
                fields=("order",),
                name="uniq_order_active_record_order",
            ),
        ),
    ]
