# Generated by Django 6.0 on 2026-08-20 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_dvdms', '0006_alter_dvdmsoutwardrecordorder_status_and_more'),
        ('emr', '0080_alter_activitydefinition_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvdmsrecorditemorder',
            name='drug',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='record_item_order', to='care_dvdms.dvdmsdrug'),
        ),
        migrations.AlterField(
            model_name='dvdmsrecordorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='DVDMSProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('mapping_type', models.CharField(choices=[('default_mapping', 'Default Mapping'), ('manual_mapping', 'Manual Mapping')], db_index=True, default='manual_mapping', max_length=20)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('drug', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='product_mapping', to='care_dvdms.dvdmsdrug')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='care_dvdms.dvdmsinstitute')),
                ('product_knowledge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dvdms_product_mappings', to='emr.productknowledge')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DVDMS Product Mappings',
            },
        ),
    ]
