# Generated by Django 6.0 on 2026-08-20 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_dvdms', '0007_alter_dvdmsrecorditemorder_drug_and_more'),
        ('emr', '0080_alter_activitydefinition_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dvdmsproductmapping',
            name='eaushadhi_drug_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='dvdmsproductmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('institute', 'eaushadhi_drug_id'), name='uniq_institute_eaushadhi_drug_id'),
        ),
    ]
