# Generated by Django 6.0 on 2026-09-01 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_dvdms', '0007_alter_dvdmsrecordorder_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvdmssynclog',
            name='sync_type',
            field=models.CharField(choices=[('save_indent', 'Save Indent'), ('track_indent', 'Track Indent'), ('fetch_issue', 'Fetch Issue'), ('acknowledge_issue', 'Acknowledge Issue')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='dvdmsinwarditemrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('record_order_item__isnull', True)), fields=('inward_record', 'drug_id', 'brand_id', 'batch'), name='uniq_inward_record_unmatched_item'),
        ),
    ]
