# Generated by Django 6.0 on 2026-09-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_dvdms", "0007_alter_dvdmsrecordorder_order_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="dvdmsinwarditemrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False), ("record_order_item__isnull", True)),
                fields=("inward_record", "drug_id", "brand_id", "batch"),
                name="uniq_inward_record_unmatched_item",
            ),
        ),
    ]
